import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { STANDARD_OBJECTS } from 'twenty-shared/metadata';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

// Builds the fixed set of standard fields for the "databaseRecordTarget" object: base system fields,
// its polymorphic "target" morph relation to every attachable standard object (mirroring
// attachment/noteTarget/taskTarget), a relation to the workspace's DatabaseConnection, the remote
// record's identity (space/base/table/record/view ids), and a refreshable preview snapshot.
export const buildDatabaseRecordTargetStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'databaseRecordTarget', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'databaseRecordTarget'>,
  FlatFieldMetadata
> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Database record target record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Remote record identity
  spaceId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'spaceId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Space Id`),
      description: i18nLabel(msg`Remote space id`),
      icon: 'IconId',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  baseId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'baseId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Base Id`),
      description: i18nLabel(msg`Remote base id`),
      icon: 'IconId',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  tableId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tableId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Table Id`),
      description: i18nLabel(msg`Remote table id`),
      icon: 'IconId',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  recordId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'recordId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Record Id`),
      description: i18nLabel(msg`Remote record id`),
      icon: 'IconId',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  viewId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'viewId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`View Id`),
      description: i18nLabel(
        msg`Remote view id the record was browsed from, if any`,
      ),
      icon: 'IconId',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Denormalized, refreshable preview snapshot
  recordName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'recordName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Record name`),
      description: i18nLabel(
        msg`Display name of the remote record at last snapshot`,
      ),
      icon: 'IconDatabase',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  baseName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'baseName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Base name`),
      description: i18nLabel(
        msg`Display name of the remote base at last snapshot`,
      ),
      icon: 'IconDatabase',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  tableName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tableName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Table name`),
      description: i18nLabel(
        msg`Display name of the remote table at last snapshot`,
      ),
      icon: 'IconDatabase',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  previewFields: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'previewFields',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Preview fields`),
      description: i18nLabel(
        msg`Up to 4 field name/value pairs from the remote record, at last snapshot`,
      ),
      icon: 'IconListDetails',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceUrl: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceUrl',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source URL`),
      description: i18nLabel(
        msg`Deep link back to the record in the cybernetics-data-centre`,
      ),
      icon: 'IconExternalLink',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  snapshotStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'snapshotStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Snapshot status`),
      description: i18nLabel(
        msg`Whether the remote record was reachable at last snapshot`,
      ),
      icon: 'IconStatusChange',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'OK'",
      options: [
        {
          id: 'de0d4957-a03c-4a81-869b-863b87cd06e8',
          value: 'OK',
          label: i18nLabel(msg`Ok`),
          position: 0,
          color: 'green',
        },
        {
          id: '697cf17a-be83-4786-b74d-9b41951a0a10',
          value: 'MISSING',
          label: i18nLabel(msg`Missing`),
          position: 1,
          color: 'orange',
        },
        {
          id: 'ffc5c324-956f-4aa6-b7bb-3830a1593388',
          value: 'FORBIDDEN',
          label: i18nLabel(msg`Forbidden`),
          position: 2,
          color: 'red',
        },
        {
          id: '0b40ff5a-df4d-4ce5-a697-87bd31a99093',
          value: 'STALE',
          label: i18nLabel(msg`Stale`),
          position: 3,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  snapshotAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'snapshotAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Snapshot date`),
      description: i18nLabel(msg`When the preview snapshot was last taken`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Morph target relations, mirroring attachment's targetX fields
  targetTask: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetTask',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'task',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetTaskId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetNote: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetNote',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'note',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetNoteId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetPerson: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetPerson',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'person',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'targetPersonId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetCompany',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'company',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'targetCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetOpportunity: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetOpportunity',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'opportunity',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'targetOpportunityId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetDashboard: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetDashboard',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'dashboard',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'targetDashboardId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetWorkflow: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.MORPH_RELATION,
      morphId:
        STANDARD_OBJECTS.databaseRecordTarget.morphIds.targetMorphId.morphId,
      fieldName: 'targetWorkflow',
      label: i18nLabel(msg`Target`),
      description: i18nLabel(msg`Database record target`),
      icon: 'IconArrowUpRight',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workflow',
      targetFieldName: 'databaseRecordTargets',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'targetWorkflowId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
